// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLFduoDNIV-_AQTrWWaaq8wdBKYwUJu0Q',
    appId: '1:335055432152:web:c1db6a01f7bbeeac47aaad',
    messagingSenderId: '335055432152',
    projectId: 'caminhodosaber-93787',
    authDomain: 'caminhodosaber-93787.firebaseapp.com',
    storageBucket: 'caminhodosaber-93787.firebasestorage.app',
    measurementId: 'G-DXMVLLLVHW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4y_0klMIFnuAkRHYEFD7-rEZSEtmIaVY',
    appId: '1:335055432152:android:75621103797e3bc547aaad',
    messagingSenderId: '335055432152',
    projectId: 'caminhodosaber-93787',
    storageBucket: 'caminhodosaber-93787.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJDA7M3R3J-rcNLiE2E-6DE045AlwXejI',
    appId: '1:335055432152:ios:b2427e3ea729497247aaad',
    messagingSenderId: '335055432152',
    projectId: 'caminhodosaber-93787',
    storageBucket: 'caminhodosaber-93787.firebasestorage.app',
    androidClientId: '335055432152-tn7toqri74dos8rdt3d5q362vejbevu7.apps.googleusercontent.com',
    iosClientId: '335055432152-76ba151nthnc27tckp26vnfl2v9hd5d8.apps.googleusercontent.com',
    iosBundleId: 'com.nelson.caminhoDoSaber',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJDA7M3R3J-rcNLiE2E-6DE045AlwXejI',
    appId: '1:335055432152:ios:b2427e3ea729497247aaad',
    messagingSenderId: '335055432152',
    projectId: 'caminhodosaber-93787',
    storageBucket: 'caminhodosaber-93787.firebasestorage.app',
    androidClientId: '335055432152-tn7toqri74dos8rdt3d5q362vejbevu7.apps.googleusercontent.com',
    iosClientId: '335055432152-76ba151nthnc27tckp26vnfl2v9hd5d8.apps.googleusercontent.com',
    iosBundleId: 'com.nelson.caminhoDoSaber',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBLFduoDNIV-_AQTrWWaaq8wdBKYwUJu0Q',
    appId: '1:335055432152:web:bc9b515b0a76436547aaad',
    messagingSenderId: '335055432152',
    projectId: 'caminhodosaber-93787',
    authDomain: 'caminhodosaber-93787.firebaseapp.com',
    storageBucket: 'caminhodosaber-93787.firebasestorage.app',
    measurementId: 'G-6V3DQB7GER',
  );
}
